import { CloudRegion } from '../types';

export const CLOUD_REGIONS: CloudRegion[] = [
  {
    id: 'aws-us-east-1',
    name: 'US East (N. Virginia)',
    provider: 'AWS',
    city: 'Ashburn',
    country: 'USA',
    lat: 39.0438,
    lng: -77.4874,
    monthlySpend: 12450,
    instancesCount: 142,
    costSavings: 18.2,
    healthScore: 97,
    carbonIntensity: 0.38,
    status: 'optimal',
    topService: 'EC2',
  },
  {
    id: 'aws-eu-west-1',
    name: 'Europe (Ireland)',
    provider: 'AWS',
    city: 'Dublin',
    country: 'Ireland',
    lat: 53.3498,
    lng: -6.2603,
    monthlySpend: 8320,
    instancesCount: 89,
    costSavings: 12.5,
    healthScore: 95,
    carbonIntensity: 0.22,
    status: 'optimal',
    topService: 'Lambda',
  },
  {
    id: 'aws-ap-south-1',
    name: 'Asia Pacific (Mumbai)',
    provider: 'AWS',
    city: 'Mumbai',
    country: 'India',
    lat: 19.076,
    lng: 72.8777,
    monthlySpend: 6780,
    instancesCount: 67,
    costSavings: 22.1,
    healthScore: 91,
    carbonIntensity: 0.65,
    status: 'warning',
    topService: 'RDS',
  },
  {
    id: 'gcp-us-central1',
    name: 'Iowa (us-central1)',
    provider: 'GCP',
    city: 'Council Bluffs',
    country: 'USA',
    lat: 41.2619,
    lng: -95.8608,
    monthlySpend: 9420,
    instancesCount: 110,
    costSavings: 15.8,
    healthScore: 98,
    carbonIntensity: 0.31,
    status: 'optimal',
    topService: 'Cloud SQL',
  },
  {
    id: 'gcp-europe-west1',
    name: 'Belgium (europe-west1)',
    provider: 'GCP',
    city: 'St. Ghislain',
    country: 'Belgium',
    lat: 50.45,
    lng: 3.82,
    monthlySpend: 5120,
    instancesCount: 54,
    costSavings: 9.4,
    healthScore: 96,
    carbonIntensity: 0.18,
    status: 'optimal',
    topService: 'Cloud Run',
  },
  {
    id: 'azure-eastus',
    name: 'East US',
    provider: 'Azure',
    city: 'Virginia',
    country: 'USA',
    lat: 37.4316,
    lng: -78.6569,
    monthlySpend: 7890,
    instancesCount: 78,
    costSavings: 14.3,
    healthScore: 94,
    carbonIntensity: 0.41,
    status: 'optimal',
    topService: 'Virtual Machines',
  },
  {
    id: 'azure-centralindia',
    name: 'Central India',
    provider: 'Azure',
    city: 'Pune',
    country: 'India',
    lat: 18.5204,
    lng: 73.8567,
    monthlySpend: 4560,
    instancesCount: 41,
    costSavings: 19.7,
    healthScore: 88,
    carbonIntensity: 0.72,
    status: 'warning',
    topService: 'Blob Storage',
  },
];
